name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
          
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
          
      - name: Install pnpm
        run: npm install -g pnpm
        
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          pnpm install
          echo "Dependencies installed"
          
      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli@latest
        
      - name: Build application
        run: |
          echo "Building application..."
          pnpm tauri build
          echo "Build completed"
        
      - name: Skip signing for now
        run: |
          echo "Skipping signing - installers will be unsigned but functional"
          
      - name: List build artifacts
        run: |
          echo "Listing all build artifacts:"
          find src-tauri/target/release/bundle -type f -name "*.exe" -o -name "*.dmg" -o -name "*.deb" -o -name "*.rpm" -o -name "*.AppImage" | head -20
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            src-tauri/target/release/bundle/nsis/*.exe
            src-tauri/target/release/bundle/dmg/*.dmg
            src-tauri/target/release/bundle/deb/*.deb
            src-tauri/target/release/bundle/rpm/*.rpm
            src-tauri/target/release/bundle/appimage/*.AppImage
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
